"""Write the reference values that the Android unit tests compare the Java preprocessing with.

The inputs are synthetic, so the file contains no Saliency4ASD data: two procedural pictures
(the pixel formula is repeated in PreprocessingParityTest.java) and a fixed list of fixations.

    python scripts/make_parity_golden.py            # rewrite the golden file
    python scripts/make_parity_golden.py --check    # exit 1 if the file is out of date
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import numpy as np
from PIL import Image

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from asd_gaze.preprocessing import IMAGE_SIZE, build_sequence, build_visual_tensor, load_stimulus  # noqa: E402

GOLDEN = REPO / 'app' / 'src' / 'test' / 'resources' / 'parity_golden.txt'
SAMPLES = 2000


def procedural_image(width: int, height: int) -> Image.Image:
    """Deterministic RGB picture with smooth ramps and fine patterns (same formula in Java)."""
    y, x = np.mgrid[0:height, 0:width].astype(np.int64)
    r = (x * 7 + y * 3) & 255
    g = ((x ^ y) * 5) & 255
    b = ((x * x + y * 13) >> 4) & 255
    return Image.fromarray(np.stack([r, g, b], axis=-1).astype(np.uint8), 'RGB')


def resize_digest(image: Image.Image) -> str:
    resized = image.resize((IMAGE_SIZE, IMAGE_SIZE), Image.BILINEAR)
    return hashlib.sha256(np.asarray(resized, dtype=np.uint8).tobytes()).hexdigest()


def fixture_fixations() -> np.ndarray:
    """30 fixations on a 1024x768 picture: more than the 25-step sequence, some off the picture."""
    rng = np.random.default_rng(2026)
    xs = rng.uniform(0, 1024, 28)
    ys = rng.uniform(0, 768, 28)
    ds = rng.choice([8.0, 42.0, 125.0, 216.0, 480.0], 28)
    fix = np.column_stack([xs, ys, ds]).astype(np.float32)
    extra = np.array([[1100.0, 900.0, 0.0], [5.0, 3.0, 333.0]], dtype=np.float32)
    return np.round(np.concatenate([fix, extra]), 3).astype(np.float32)


def render() -> str:
    main = procedural_image(1024, 768)
    portrait = procedural_image(683, 1024)
    fixations = fixture_fixations()

    seq = build_sequence(fixations)
    visual = build_visual_tensor(load_stimulus(main), fixations).reshape(-1)
    rng = np.random.default_rng(7)
    idx = np.sort(rng.choice(visual.size, SAMPLES, replace=False))

    lines = ['# Generated by scripts/make_parity_golden.py from asd_gaze/preprocessing.py. Do not edit.']
    lines.append(f'image 1024 768 {resize_digest(main)}')
    lines.append(f'image 683 1024 {resize_digest(portrait)}')
    lines.append(f'fixations {len(fixations)}')
    lines += [f'{x:.3f} {y:.3f} {d:.3f}' for x, y, d in fixations]
    lines.append('gaze_seq ' + ' '.join(f'{v:.8f}' for v in seq.reshape(-1)))
    lines.append(f'visual_sum {float(visual.astype(np.float64).sum()):.6f}')
    lines.append(f'visual_samples {SAMPLES}')
    lines += [f'{i} {visual[i]:.8f}' for i in idx]
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='fail if the golden file is out of date')
    args = parser.parse_args()
    text = render()
    if args.check:
        if not GOLDEN.exists() or GOLDEN.read_text() != text:
            sys.exit(f'{GOLDEN} is out of date: run python scripts/make_parity_golden.py')
        print(f'{GOLDEN} is up to date')
        return
    GOLDEN.write_text(text)
    print(f'wrote {GOLDEN}')


if __name__ == '__main__':
    main()
